'use strict';

/**
 * Cross-language end-to-end contract.
 *
 * The fixture here is generated by the Kotlin side (SyncPayloadTest pins it, and
 * `./gradlew :domain:test -DupdateFixture=true` regenerates it). These tests push it
 * through the real Apps Script functions, so the two halves are checked against each other
 * rather than each merely being self-consistent.
 *
 * Caveat worth knowing: in production the digest reads rows back out of the sheet via
 * getDisplayValues(), so amounts arrive as formatted strings like "$250.00" rather than as
 * the JSON numbers in this payload. The selection logic keys off date strings and the paid
 * flag, which are identical in both shapes; a case covering the display-string form is
 * included below.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { loadAppsScript } = require('./harness');

const gs = loadAppsScript().context;

const payload = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'sync-payload.json'), 'utf8')
).payload;

/** The date the fixture is built around; two different plans fall due on it. */
const CANONICAL_TODAY = '2026-03-15';

test('the fixture is a sync request the endpoint would accept', () => {
  assert.ok(Array.isArray(payload.bills));
  assert.ok(Array.isArray(payload.occurrences));
  assert.equal(payload.bills.length, 2);
});

test('every row carries exactly the columns this script expects', () => {
  payload.occurrences.forEach((row) => {
    assert.deepEqual(
      Object.keys(row),
      gs.OCCURRENCE_COLUMNS,
      'occurrence columns must match OCCURRENCE_COLUMNS in order'
    );
  });
  payload.bills.forEach((row) => {
    assert.deepEqual(Object.keys(row), gs.BILL_COLUMNS);
  });
});

test('dates arrive as yyyy-MM-dd strings, which is what the digest compares', () => {
  payload.occurrences.forEach((row) => {
    assert.match(row.due_date, /^\d{4}-\d{2}-\d{2}$/, `bad due_date: ${row.due_date}`);
  });
});

test('the digest finds both plans falling due on the same day', () => {
  const due = gs.selectDueRows(payload.occurrences, CANONICAL_TODAY);
  assert.deepEqual(
    due.map((r) => r.occurrence_id).sort(),
    ['car-loan#3', 'dentist#2'],
    'a monthly and a bi-weekly plan both land on this date'
  );
});

test('a payment the app marked paid is not announced', () => {
  // car-loan#1 is due 2026-01-15 and was marked paid on the Kotlin side.
  const due = gs.selectDueRows(payload.occurrences, '2026-01-15');
  assert.deepEqual(due, [], 'paid installments must never appear in the digest');
});

test('a quiet day produces nothing to send', () => {
  assert.deepEqual(gs.selectDueRows(payload.occurrences, '2026-06-01'), []);
});

test('the subject line totals what is actually due', () => {
  const due = gs.selectDueRows(payload.occurrences, CANONICAL_TODAY);
  const subject = gs.buildDigestSubject(due, CANONICAL_TODAY);
  // $250.00 car loan + $125.00 dentist
  assert.match(subject, /^2 payments due today — \$375\.00/);
});

test('the email body names both bills and their progress', () => {
  const due = gs.selectDueRows(payload.occurrences, CANONICAL_TODAY);
  const html = gs.buildDigestHtml(due, CANONICAL_TODAY, 0);
  assert.match(html, /Car loan/);
  assert.match(html, /Dentist payment plan/);
  assert.match(html, /Payment 3 of 4/);
  assert.match(html, /Payment 2 of 3/);
});

test('selection is unchanged when amounts arrive as sheet display strings', () => {
  const asDisplayed = payload.occurrences.map((row) =>
    Object.assign({}, row, {
      amount: '$' + Number(row.amount).toFixed(2),
      paid: row.paid ? 'TRUE' : 'FALSE',
    })
  );
  const due = gs.selectDueRows(asDisplayed, CANONICAL_TODAY);
  assert.deepEqual(due.map((r) => r.occurrence_id).sort(), ['car-loan#3', 'dentist#2']);
  assert.equal(gs.sumDisplayAmounts(due), '$375.00');
});

test('a sync round trip preserves notified_on and keeps the digest idempotent', () => {
  // Simulate: the digest already ran today and stamped both rows...
  const inSheet = payload.occurrences.map((row) =>
    Object.assign({}, row, {
      notified_on: row.due_date === CANONICAL_TODAY ? CANONICAL_TODAY : '',
    })
  );
  // ...then the phone syncs, sending notified_on empty as it always does.
  const merged = gs.restoreScriptOwnedColumns(
    payload.occurrences,
    gs.collectScriptOwnedColumns(inSheet)
  );

  assert.deepEqual(
    gs.selectDueRows(merged, CANONICAL_TODAY),
    [],
    'a sync must not cause the same payments to be emailed twice'
  );
});

test('the phone always sends notified_on empty, leaving the column to this script', () => {
  payload.occurrences.forEach((row) => {
    assert.equal(row.notified_on, '', `${row.occurrence_id} should not carry notified_on`);
  });
});

test('the final installment carries the remainder amount', () => {
  const last = payload.occurrences.find((r) => r.occurrence_id === 'car-loan#4');
  assert.equal(Number(last.amount), 245, 'final payment differs from the regular installment');
});

test('bill rows expose payoff progress for whoever reads the sheet directly', () => {
  const carLoan = payload.bills.find((b) => b.bill_id === 'car-loan');
  assert.equal(carLoan.installment_count, 4);
  assert.equal(carLoan.paid_count, 1);
  assert.equal(Number(carLoan.remaining_amount), 745);
  assert.equal(carLoan.next_due, '2026-02-15');
  assert.equal(carLoan.schedule, 'Monthly');

  const dentist = payload.bills.find((b) => b.bill_id === 'dentist');
  assert.equal(dentist.schedule, 'Every 2 weeks');
  assert.equal(dentist.autopay, true);
});
